services:
  humble:
    image: ${ROS_HUMBLE_IMAGE:-ros-rbs-humble:dev}
    build:
      context: ./docker/humble
      args:
        ROS_HUMBLE_BASE_IMAGE: ${ROS_HUMBLE_BASE_IMAGE:-osrf/ros:humble-desktop}
        UBUNTU_APT_MIRROR: ${UBUNTU_APT_MIRROR:-https://mirrors.tuna.tsinghua.edu.cn/ubuntu}
        ROS_APT_MIRROR: ${ROS_APT_MIRROR:-https://mirrors.tuna.tsinghua.edu.cn/ros2/ubuntu}
        PIP_INDEX_URL: ${PIP_INDEX_URL:-https://pypi.tuna.tsinghua.edu.cn/simple}
        ROSDEP_SOURCE_MIRROR: ${ROSDEP_SOURCE_MIRROR:-https://mirrors.tuna.tsinghua.edu.cn/github-raw/ros/rosdistro/master/rosdep}
        ROSDISTRO_INDEX_URL: ${ROSDISTRO_INDEX_URL:-https://mirrors.tuna.tsinghua.edu.cn/rosdistro/index-v4.yaml}
    network_mode: host
    ipc: host
    working_dir: /ws
    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
    volumes:
      - .:/ws
      - ./.ros_home:/root/.ros
    command: bash -l

  humble-x11:
    profiles:
      - x11
    extends:
      service: humble
    environment:
      DISPLAY: ${DISPLAY:-}
      QT_X11_NO_MITSHM: "1"
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
      ROS_HUMBLE_ENABLE_X11: ${ROS_HUMBLE_ENABLE_X11:-1}
    volumes:
      - .:/ws
      - ./.ros_home:/root/.ros
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
