import { PROOF_FLAGS } from "../shared/contracts";
import type {
  O7BoardMediaPreflightSummary,
  O7ElevatorStateSnapshot,
  O7LabelingQueueSnapshot,
  O7OperatorConsoleResponse,
  O7OperatorKrView,
  O7RealtimeMapSnapshot,
  O7RouteReplaySnapshot,
} from "../shared/contracts";

const CONTRACT_SOURCE = "cloud-relay/src/ros2_trashbot_cloud_relay/remote_cloud_relay.py" as const;

const KR_VIEWS: O7OperatorKrView[] = [
  {
    id: "O7-KR1",
    title: "实时地图与机器人位置",
    status: "blocked",
    cloud_contract: "realtime.map_pose.v1",
    pc_surface: "Map/Pose panel",
    current_view: ["map_ref=draft", "pose=not_proven", "route_membership=blocked"],
    blocked_by: ["cloud realtime stream not connected", "ROS2 /tf forwarding not proven"],
    next_required_contract: "Cloud must expose robot pose snapshots with map frame and freshness timestamp.",
  },
  {
    id: "O7-KR2",
    title: "电梯状态展示",
    status: "blocked",
    cloud_contract: "realtime.elevator_state.v1",
    pc_surface: "Elevator state panel",
    current_view: ["state_chain=draft", "floor_evidence=not_proven", "handoff_reason=blocked"],
    blocked_by: ["elevator event archive not connected", "real elevator evidence not proven"],
    next_required_contract: "Cloud must expose elevator state chain and evidence refs per task.",
  },
  {
    id: "O7-KR3",
    title: "历史路线回放",
    status: "draft",
    cloud_contract: "history.route_replay.v1",
    pc_surface: "Route replay panel",
    current_view: ["task_selector=draft", "trajectory_frames=not_proven", "playback=blocked"],
    blocked_by: ["cloud task archive query not connected", "trajectory frame schema pending"],
    next_required_contract: "Cloud must expose task list, trajectory frames, and timestamped state transitions.",
  },
  {
    id: "O7-KR4",
    title: "数据标注/打标界面",
    status: "draft",
    cloud_contract: "labeling.review_queue.v1",
    pc_surface: "Labeling queue panel",
    current_view: ["queue=draft", "label_schema=not_proven", "submit=blocked"],
    blocked_by: ["annotation API not connected", "training dataset export not proven"],
    next_required_contract: "Cloud must expose review queue, label schema, and submit/rollback audit trail.",
  },
  {
    id: "O7-KR5",
    title: "实时 ASR 监听 + TTS 发言控制",
    status: "blocked",
    cloud_contract: "voice.asr_tts_operator.v1",
    pc_surface: "Voice monitor panel",
    current_view: ["asr_stream=blocked", "tts_draft=not_proven", "speaker_dispatch=blocked"],
    blocked_by: ["ASR event stream not connected", "TTS command ACK contract pending"],
    next_required_contract: "Cloud must expose ASR transcript events and TTS draft command ACK without direct robot control.",
  },
  {
    id: "O7-KR6",
    title: "手动转向控制 + 自动寻路下发",
    status: "blocked",
    cloud_contract: "operator.safe_command_preview.v1",
    pc_surface: "Safe command preview panel",
    current_view: ["manual_control=blocked", "navigate_goal=blocked", "ack=not_proven"],
    blocked_by: ["safe command dispatch disabled", "robot-side ACK and recovery path not proven"],
    next_required_contract: "Cloud must expose idempotent safe command API with confirmation, ACK, timeout, and cancel recovery.",
  },
];

const BOARD_MEDIA_PREFLIGHT_SUMMARY: O7BoardMediaPreflightSummary = {
  schema: "trashbot.o7_board_media_preflight.v1",
  schema_version: 1,
  evidence_boundary: "software_proof_o7_board_media_preflight_contract",
  source: "operator_media_preflight",
  overall_state: "blocked",
  safe_to_control: false,
  primary_actions_enabled: false,
  device_probe_allowed: false,
  device_probe_attempted: false,
  software_proof_only: true,
  blocked_reasons: [
    "board_media_preflight_not_collected_by_pc",
    "rtc_signaling_stun_turn_not_proven",
    "camera_video_source_not_proven",
    "audio_input_output_not_proven",
    "asr_tts_runtime_not_proven",
  ],
  not_proven: [
    "real_rtc_session",
    "real_camera_video_source",
    "real_audio_capture",
    "real_audio_playback",
    "real_asr_stream",
    "real_tts_playback",
    "orange_pi_media_runtime",
    "on_robot_media_smoke",
  ],
  next_required_evidence: [
    "resolve_blocked_preflight_items",
    "orange_pi_camera_device_enumeration",
    "orange_pi_audio_input_output_enumeration",
    "rtc_signaling_stun_turn_trace",
    "camera_frame_evidence_with_timestamp",
    "asr_partial_and_final_transcript_trace",
    "tts_audio_playback_trace",
    "cpu_encoding_budget_trace",
    "on_robot_media_smoke_with_no_chassis_motion",
  ],
};

const REALTIME_MAP_SNAPSHOT: O7RealtimeMapSnapshot = {
  schema: "trashbot.o7.realtime_map_snapshot.v1",
  schema_version: 1,
  source: "software_proof",
  snapshot_status: "blocked_not_proven",
  safe_to_control: false,
  primary_actions_enabled: false,
  map_ref: {
    value: "not_connected",
    status: "not_proven",
    evidence_ref: "missing_cloud_realtime_map_ref",
  },
  map_frame: {
    value: "map",
    status: "contract_placeholder_not_tf",
    frame_source: "cloud_contract_draft",
  },
  robot_pose: {
    x_m: null,
    y_m: null,
    yaw_rad: null,
    pose_source: "not_connected",
    status: "not_proven",
  },
  pose_freshness: {
    last_update_ms: null,
    age_ms: null,
    latency_lt_2s_proven: false,
    status: "blocked_no_realtime_stream",
  },
  route_membership: {
    route_id: "not_connected",
    on_route: false,
    in_elevator_zone: false,
    status: "not_proven",
    reason: "cloud_realtime_map_pose_stream_not_connected",
  },
  blocked_reasons: [
    "cloud_realtime_api_draft",
    "ros2_tf_forwarding_not_proven",
    "map_artifact_not_connected",
    "robot_position_latency_lt_2s_not_proven",
  ],
  not_proven: [
    "real_ros2_tf",
    "real_map_artifact",
    "real_robot_pose",
    "real_route_membership",
    "real_elevator_zone_membership",
    "robot_position_latency_lt_2s",
  ],
};

const ELEVATOR_STATE_SNAPSHOT: O7ElevatorStateSnapshot = {
  schema: "trashbot.o7.elevator_state_snapshot.v1",
  schema_version: 1,
  source: "software_proof",
  snapshot_status: "blocked_not_proven",
  safe_to_control: false,
  primary_actions_enabled: false,
  state_chain: [
    {
      state: "not_connected",
      status: "not_proven",
      evidence_ref: "missing_cloud_elevator_state_chain",
    },
  ],
  current_state: "not_connected",
  current_floor_evidence: {
    floor_label: "not_connected",
    confidence: null,
    evidence_ref: "missing_floor_evidence",
    status: "not_proven",
  },
  target_floor: {
    floor_label: "not_connected",
    confirmation_status: "not_proven",
  },
  human_takeover: {
    required: true,
    reason: "real_elevator_state_chain_not_proven",
    operator_action: "keep_observe_only_until_cloud_archive_and_field_evidence_exist",
  },
  blocked_reasons: [
    "elevator_event_archive_not_connected",
    "real_elevator_door_state_not_proven",
    "floor_recognition_not_proven",
    "human_takeover_reason_not_backfilled_from_task_record",
  ],
  not_proven: [
    "real_elevator_state_chain",
    "real_current_floor",
    "real_target_floor_confirmation",
    "real_elevator_arrival",
    "real_human_takeover_reason",
  ],
};

const ROUTE_REPLAY_SNAPSHOT: O7RouteReplaySnapshot = {
  schema: "trashbot.o7.route_replay_snapshot.v1",
  schema_version: 1,
  source: "software_proof",
  snapshot_status: "blocked_not_proven",
  safe_to_control: false,
  primary_actions_enabled: false,
  playback_available: false,
  real_archive_connected: false,
  task_selector: {
    source_contract: "history.route_replay.v1",
    status: "blocked_no_cloud_task_archive",
    available_task_count: 0,
    selected_task_id: "not_connected",
    task_list_ref: "missing_o6_cloud_task_archive",
    selection_required: true,
  },
  selected_task: {
    task_id: "not_connected",
    robot_id: "not_connected",
    route_id: "not_connected",
    started_at_ms: null,
    completed_at_ms: null,
    status: "not_proven",
    evidence_ref: "missing_selected_task_record",
  },
  trajectory: {
    frame_count: 0,
    sample_frames: [],
    frame_schema: "pending_cloud_trajectory_frame_v1",
    map_frame: "not_connected",
    status: "blocked_no_trajectory_api",
  },
  playback_cursor: {
    frame_index: null,
    timestamp_ms: null,
    playing: false,
    speed: 0,
    status: "blocked_not_available",
  },
  keyframes: {
    count: 0,
    sample_refs: [],
    status: "blocked_no_keyframe_archive",
  },
  evidence_refs: {
    task_archive: "missing_o6_cloud_task_archive",
    trajectory_api: "missing_trajectory_api",
    keyframe_archive: "missing_keyframe_archive",
    state_transition_archive: "missing_state_transition_archive",
  },
  state_transitions: {
    count: 0,
    sample: [],
    status: "blocked_no_state_transition_archive",
    gaps: [
      "cloud_task_archive_not_connected",
      "trajectory_frame_schema_not_backfilled",
      "keyframe_evidence_refs_not_backfilled",
      "state_transition_timeline_not_backfilled",
    ],
  },
  blocked_reasons: [
    "o6_cloud_task_archive_not_connected",
    "history_route_replay_api_draft",
    "trajectory_frames_not_available",
    "keyframe_evidence_refs_not_available",
    "state_transitions_not_available",
  ],
  not_proven: [
    "real_history_task_list",
    "real_selected_task",
    "real_trajectory_frames",
    "real_route_playback_cursor",
    "real_keyframe_evidence_refs",
    "real_state_transition_timeline",
    "cloud_archive_query_latency",
  ],
  next_required_evidence: [
    "o6_cloud_task_archive_query_contract",
    "history_route_replay_task_list_fixture",
    "trajectory_frame_schema_with_map_frame_and_timestamp",
    "keyframe_evidence_ref_archive_sample",
    "state_transition_timeline_archive_sample",
    "pc_playback_cursor_bound_to_cloud_frames_without_robot_control",
  ],
};

const LABELING_QUEUE_SNAPSHOT: O7LabelingQueueSnapshot = {
  schema: "trashbot.o7.labeling_queue_snapshot.v1",
  schema_version: 1,
  source: "software_proof",
  snapshot_status: "blocked_not_proven",
  safe_to_control: false,
  primary_actions_enabled: false,
  submit_enabled: false,
  rollback_enabled: false,
  real_annotation_api_connected: false,
  dataset_export_available: false,
  review_queue: {
    source_contract: "labeling.review_queue.v1",
    status: "blocked_no_annotation_api",
    available_item_count: 0,
    assigned_operator: "not_connected",
    queue_ref: "missing_o6_annotation_review_queue",
    selection_required: true,
  },
  selected_item: {
    item_id: "not_connected",
    task_id: "not_connected",
    frame_id: "not_connected",
    media_ref: "missing_review_item_media_ref",
    evidence_ref: "missing_selected_labeling_item_record",
    status: "not_proven",
  },
  label_schema: {
    schema_ref: "missing_label_schema",
    version: "not_connected",
    status: "blocked_no_label_schema_api",
    required_fields: [],
  },
  allowed_label_types: [
    {
      type: "elevator_door_state",
      status: "contract_placeholder_not_api",
      values: ["open", "closed", "unknown"],
    },
    {
      type: "floor_label",
      status: "contract_placeholder_not_api",
      values: [],
    },
    {
      type: "obstacle_type",
      status: "contract_placeholder_not_api",
      values: ["none", "person", "cart", "trash_bag", "unknown"],
    },
  ],
  draft_labels: {
    count: 0,
    items: [],
    status: "blocked_no_selected_item",
    autosave_available: false,
  },
  submit_audit: {
    status: "blocked_not_available",
    endpoint: "POST /api/o6/annotations (future, disabled)",
    last_submit_id: "not_connected",
    idempotency_key_required: true,
    audit_ref: "missing_submit_audit_log",
  },
  rollback_audit: {
    status: "blocked_not_available",
    endpoint: "POST /api/o6/annotations/rollback (future, disabled)",
    last_rollback_id: "not_connected",
    requires_reason: true,
    audit_ref: "missing_rollback_audit_log",
  },
  dataset_export: {
    status: "blocked_not_available",
    export_ref: "missing_training_dataset_export",
    supported_formats: [],
    gaps: [
      "o6_annotation_api_not_connected",
      "accepted_label_schema_not_proven",
      "reviewed_items_not_available",
      "dataset_manifest_export_not_available",
      "training_split_policy_not_defined",
    ],
  },
  blocked_reasons: [
    "o6_annotation_api_not_connected",
    "labeling_review_queue_api_draft",
    "label_schema_not_available",
    "selected_review_item_not_available",
    "submit_audit_not_available",
    "rollback_audit_not_available",
    "training_dataset_export_not_available",
  ],
  not_proven: [
    "real_labeling_review_queue",
    "real_selected_labeling_item",
    "real_frame_or_screenshot_media",
    "real_label_schema",
    "real_allowed_label_types_from_cloud",
    "real_draft_label_autosave",
    "real_annotation_submit",
    "real_annotation_rollback",
    "real_training_dataset_export",
  ],
  next_required_evidence: [
    "o6_annotation_review_queue_query_contract",
    "label_schema_fixture_with_allowed_types",
    "selected_review_item_with_media_evidence_ref",
    "draft_label_payload_schema",
    "submit_annotation_audit_log_sample",
    "rollback_annotation_audit_log_sample",
    "dataset_export_manifest_contract",
    "pc_labeling_panel_bound_to_cloud_api_without_robot_control",
  ],
};

export function buildO7OperatorConsoleResponse(): O7OperatorConsoleResponse {
  // 这里与 cloud-relay helper 固定同一 schema；PC 只消费契约快照，不连接小车。
  // 六个 KR 都保留 draft/blocked/not_proven，避免 UI 把占位面板外推成真实 O7 能力。
  // 板端媒体 preflight 暂用静态 fail-closed 摘要，直到 cloud 提供真实板端 JSON。
  // 地图和电梯 snapshot 只让 operator 看见字段契约，不能被前端解释为 ROS2 实时流。
  // 路线回放 snapshot 只锁定 O6 归档 API 的对接字段，当前不能渲染为可播放历史任务。
  // 标注队列 snapshot 只锁定 O6 annotation/export 对接字段，提交和回滚固定 fail-closed。
  return {
    schema: "trashbot.o7.operator_console.v1",
    ...PROOF_FLAGS,
    contract_source: CONTRACT_SOURCE,
    workstation_endpoint: "/api/o7/operator-console",
    cloud_api_status: "draft_blocked_not_proven",
    robot_connection: "not_connected_by_pc",
    realtime_stream_status: "blocked_not_proven",
    operator_mode: "observe_only",
    board_media_preflight_required: true,
    board_media_preflight_schema: "trashbot.o7_board_media_preflight.v1",
    board_media_preflight_state: "blocked",
    board_media_preflight_summary: BOARD_MEDIA_PREFLIGHT_SUMMARY,
    realtime_map_snapshot: REALTIME_MAP_SNAPSHOT,
    elevator_state_snapshot: ELEVATOR_STATE_SNAPSHOT,
    route_replay_snapshot: ROUTE_REPLAY_SNAPSHOT,
    labeling_queue_snapshot: LABELING_QUEUE_SNAPSHOT,
    manual_control_policy: {
      pc_direct_robot_connection: false,
      cloud_mediated_only: true,
      command_dispatch_enabled: false,
      confirmation_required_before_future_dispatch: true,
      success_claim_allowed: false,
    },
    kr_views: KR_VIEWS,
    command_previews: [
      {
        id: "manual_turn_preview",
        label: "Manual turn envelope",
        status: "blocked_not_proven",
        requires_confirmation: true,
        sends_to_robot: false,
        cloud_endpoint: "POST /api/o7/operator/commands/manual-turn (future, disabled)",
        recovery_path: "Keep observe_only mode until Robot/Hardware provide ACK, timeout, and stop evidence.",
      },
      {
        id: "navigate_goal_preview",
        label: "Navigate goal envelope",
        status: "blocked_not_proven",
        requires_confirmation: true,
        sends_to_robot: false,
        cloud_endpoint: "POST /api/o7/operator/commands/navigate-goal (future, disabled)",
        recovery_path: "Require cloud idempotency key, robot ACK, cancel path, and task archive evidence before enabling.",
      },
      {
        id: "tts_preview",
        label: "TTS utterance envelope",
        status: "blocked_not_proven",
        requires_confirmation: true,
        sends_to_robot: false,
        cloud_endpoint: "POST /api/o7/operator/voice/tts (future, disabled)",
        recovery_path: "Require cloud TTS ACK and speaker-side failure event before any dispatch UI.",
      },
    ],
    blocked_reasons: [
      "cloud_realtime_api_draft",
      "pc_must_not_direct_connect_robot",
      "robot_ack_timeout_recovery_not_proven",
      "real_map_pose_stream_not_proven",
      "realtime_map_snapshot_blocked",
      "elevator_state_snapshot_blocked",
      "route_replay_snapshot_blocked",
      "labeling_queue_snapshot_blocked",
      "o6_cloud_task_archive_not_connected",
      "o6_annotation_api_not_connected",
      "real_voice_stream_not_proven",
      "board_media_preflight_blocked",
      "manual_or_navigation_dispatch_disabled",
    ],
    not_proven: [
      "real_o7_realtime_cloud_stream",
      "real_robot_position_latency_lt_2s",
      "real_elevator_state_chain",
      "real_route_replay_archive",
      "real_route_replay_task_selector",
      "real_route_replay_trajectory_frames",
      "real_route_replay_state_transitions",
      "real_labeling_review_queue",
      "real_selected_labeling_item",
      "real_annotation_submit_api",
      "real_annotation_rollback",
      "real_training_dataset_export",
      "real_asr_tts_runtime",
      "real_rtc_session",
      "real_camera_video_source",
      "real_audio_capture",
      "real_audio_playback",
      "real_tts_playback",
      "on_robot_media_smoke",
      "real_operator_safe_command_dispatch",
      "delivery_success",
    ],
    recovery_paths: [
      "Connect O6 cloud archive and realtime stream before replacing draft values.",
      "Connect O6 annotation API, submit audit, rollback audit, and dataset export before enabling labeling actions.",
      "Collect board media preflight JSON and on-robot media smoke before interpreting KR5 fields.",
      "Ask Robot Software for robot-side ACK, timeout, cancel, and stop evidence before enabling commands.",
      "Ask Hardware for HIL/safety evidence before treating manual control as safe.",
    ],
  };
}
