import { PROOF_FLAGS } from "../shared/contracts";
import type {
  O7BoardMediaPreflightSummary,
  O7ElevatorStateSnapshot,
  O7OperatorConsoleResponse,
  O7OperatorKrView,
  O7RealtimeMapSnapshot,
} from "../shared/contracts";

const CONTRACT_SOURCE = "cloud-relay/src/ros2_trashbot_cloud_relay/remote_cloud_relay.py" as const;

const KR_VIEWS: O7OperatorKrView[] = [
  {
    id: "O7-KR1",
    title: "实时地图与机器人位置",
    status: "blocked",
    cloud_contract: "realtime.map_pose.v1",
    pc_surface: "Map/Pose panel",
    current_view: ["map_ref=draft", "pose=not_proven", "route_membership=blocked"],
    blocked_by: ["cloud realtime stream not connected", "ROS2 /tf forwarding not proven"],
    next_required_contract: "Cloud must expose robot pose snapshots with map frame and freshness timestamp.",
  },
  {
    id: "O7-KR2",
    title: "电梯状态展示",
    status: "blocked",
    cloud_contract: "realtime.elevator_state.v1",
    pc_surface: "Elevator state panel",
    current_view: ["state_chain=draft", "floor_evidence=not_proven", "handoff_reason=blocked"],
    blocked_by: ["elevator event archive not connected", "real elevator evidence not proven"],
    next_required_contract: "Cloud must expose elevator state chain and evidence refs per task.",
  },
  {
    id: "O7-KR3",
    title: "历史路线回放",
    status: "draft",
    cloud_contract: "history.route_replay.v1",
    pc_surface: "Route replay panel",
    current_view: ["task_selector=draft", "trajectory_frames=not_proven", "playback=blocked"],
    blocked_by: ["cloud task archive query not connected", "trajectory frame schema pending"],
    next_required_contract: "Cloud must expose task list, trajectory frames, and timestamped state transitions.",
  },
  {
    id: "O7-KR4",
    title: "数据标注/打标界面",
    status: "draft",
    cloud_contract: "labeling.review_queue.v1",
    pc_surface: "Labeling queue panel",
    current_view: ["queue=draft", "label_schema=not_proven", "submit=blocked"],
    blocked_by: ["annotation API not connected", "training dataset export not proven"],
    next_required_contract: "Cloud must expose review queue, label schema, and submit/rollback audit trail.",
  },
  {
    id: "O7-KR5",
    title: "实时 ASR 监听 + TTS 发言控制",
    status: "blocked",
    cloud_contract: "voice.asr_tts_operator.v1",
    pc_surface: "Voice monitor panel",
    current_view: ["asr_stream=blocked", "tts_draft=not_proven", "speaker_dispatch=blocked"],
    blocked_by: ["ASR event stream not connected", "TTS command ACK contract pending"],
    next_required_contract: "Cloud must expose ASR transcript events and TTS draft command ACK without direct robot control.",
  },
  {
    id: "O7-KR6",
    title: "手动转向控制 + 自动寻路下发",
    status: "blocked",
    cloud_contract: "operator.safe_command_preview.v1",
    pc_surface: "Safe command preview panel",
    current_view: ["manual_control=blocked", "navigate_goal=blocked", "ack=not_proven"],
    blocked_by: ["safe command dispatch disabled", "robot-side ACK and recovery path not proven"],
    next_required_contract: "Cloud must expose idempotent safe command API with confirmation, ACK, timeout, and cancel recovery.",
  },
];

const BOARD_MEDIA_PREFLIGHT_SUMMARY: O7BoardMediaPreflightSummary = {
  schema: "trashbot.o7_board_media_preflight.v1",
  schema_version: 1,
  evidence_boundary: "software_proof_o7_board_media_preflight_contract",
  source: "operator_media_preflight",
  overall_state: "blocked",
  safe_to_control: false,
  primary_actions_enabled: false,
  device_probe_allowed: false,
  device_probe_attempted: false,
  software_proof_only: true,
  blocked_reasons: [
    "board_media_preflight_not_collected_by_pc",
    "rtc_signaling_stun_turn_not_proven",
    "camera_video_source_not_proven",
    "audio_input_output_not_proven",
    "asr_tts_runtime_not_proven",
  ],
  not_proven: [
    "real_rtc_session",
    "real_camera_video_source",
    "real_audio_capture",
    "real_audio_playback",
    "real_asr_stream",
    "real_tts_playback",
    "orange_pi_media_runtime",
    "on_robot_media_smoke",
  ],
  next_required_evidence: [
    "resolve_blocked_preflight_items",
    "orange_pi_camera_device_enumeration",
    "orange_pi_audio_input_output_enumeration",
    "rtc_signaling_stun_turn_trace",
    "camera_frame_evidence_with_timestamp",
    "asr_partial_and_final_transcript_trace",
    "tts_audio_playback_trace",
    "cpu_encoding_budget_trace",
    "on_robot_media_smoke_with_no_chassis_motion",
  ],
};

const REALTIME_MAP_SNAPSHOT: O7RealtimeMapSnapshot = {
  schema: "trashbot.o7.realtime_map_snapshot.v1",
  schema_version: 1,
  source: "software_proof",
  snapshot_status: "blocked_not_proven",
  safe_to_control: false,
  primary_actions_enabled: false,
  map_ref: {
    value: "not_connected",
    status: "not_proven",
    evidence_ref: "missing_cloud_realtime_map_ref",
  },
  map_frame: {
    value: "map",
    status: "contract_placeholder_not_tf",
    frame_source: "cloud_contract_draft",
  },
  robot_pose: {
    x_m: null,
    y_m: null,
    yaw_rad: null,
    pose_source: "not_connected",
    status: "not_proven",
  },
  pose_freshness: {
    last_update_ms: null,
    age_ms: null,
    latency_lt_2s_proven: false,
    status: "blocked_no_realtime_stream",
  },
  route_membership: {
    route_id: "not_connected",
    on_route: false,
    in_elevator_zone: false,
    status: "not_proven",
    reason: "cloud_realtime_map_pose_stream_not_connected",
  },
  blocked_reasons: [
    "cloud_realtime_api_draft",
    "ros2_tf_forwarding_not_proven",
    "map_artifact_not_connected",
    "robot_position_latency_lt_2s_not_proven",
  ],
  not_proven: [
    "real_ros2_tf",
    "real_map_artifact",
    "real_robot_pose",
    "real_route_membership",
    "real_elevator_zone_membership",
    "robot_position_latency_lt_2s",
  ],
};

const ELEVATOR_STATE_SNAPSHOT: O7ElevatorStateSnapshot = {
  schema: "trashbot.o7.elevator_state_snapshot.v1",
  schema_version: 1,
  source: "software_proof",
  snapshot_status: "blocked_not_proven",
  safe_to_control: false,
  primary_actions_enabled: false,
  state_chain: [
    {
      state: "not_connected",
      status: "not_proven",
      evidence_ref: "missing_cloud_elevator_state_chain",
    },
  ],
  current_state: "not_connected",
  current_floor_evidence: {
    floor_label: "not_connected",
    confidence: null,
    evidence_ref: "missing_floor_evidence",
    status: "not_proven",
  },
  target_floor: {
    floor_label: "not_connected",
    confirmation_status: "not_proven",
  },
  human_takeover: {
    required: true,
    reason: "real_elevator_state_chain_not_proven",
    operator_action: "keep_observe_only_until_cloud_archive_and_field_evidence_exist",
  },
  blocked_reasons: [
    "elevator_event_archive_not_connected",
    "real_elevator_door_state_not_proven",
    "floor_recognition_not_proven",
    "human_takeover_reason_not_backfilled_from_task_record",
  ],
  not_proven: [
    "real_elevator_state_chain",
    "real_current_floor",
    "real_target_floor_confirmation",
    "real_elevator_arrival",
    "real_human_takeover_reason",
  ],
};

export function buildO7OperatorConsoleResponse(): O7OperatorConsoleResponse {
  // 这里与 cloud-relay helper 固定同一 schema；PC 只消费契约快照，不连接小车。
  // 六个 KR 都保留 draft/blocked/not_proven，避免 UI 把占位面板外推成真实 O7 能力。
  // 板端媒体 preflight 暂用静态 fail-closed 摘要，直到 cloud 提供真实板端 JSON。
  // 地图和电梯 snapshot 只让 operator 看见字段契约，不能被前端解释为 ROS2 实时流。
  return {
    schema: "trashbot.o7.operator_console.v1",
    ...PROOF_FLAGS,
    contract_source: CONTRACT_SOURCE,
    workstation_endpoint: "/api/o7/operator-console",
    cloud_api_status: "draft_blocked_not_proven",
    robot_connection: "not_connected_by_pc",
    realtime_stream_status: "blocked_not_proven",
    operator_mode: "observe_only",
    board_media_preflight_required: true,
    board_media_preflight_schema: "trashbot.o7_board_media_preflight.v1",
    board_media_preflight_state: "blocked",
    board_media_preflight_summary: BOARD_MEDIA_PREFLIGHT_SUMMARY,
    realtime_map_snapshot: REALTIME_MAP_SNAPSHOT,
    elevator_state_snapshot: ELEVATOR_STATE_SNAPSHOT,
    manual_control_policy: {
      pc_direct_robot_connection: false,
      cloud_mediated_only: true,
      command_dispatch_enabled: false,
      confirmation_required_before_future_dispatch: true,
      success_claim_allowed: false,
    },
    kr_views: KR_VIEWS,
    command_previews: [
      {
        id: "manual_turn_preview",
        label: "Manual turn envelope",
        status: "blocked_not_proven",
        requires_confirmation: true,
        sends_to_robot: false,
        cloud_endpoint: "POST /api/o7/operator/commands/manual-turn (future, disabled)",
        recovery_path: "Keep observe_only mode until Robot/Hardware provide ACK, timeout, and stop evidence.",
      },
      {
        id: "navigate_goal_preview",
        label: "Navigate goal envelope",
        status: "blocked_not_proven",
        requires_confirmation: true,
        sends_to_robot: false,
        cloud_endpoint: "POST /api/o7/operator/commands/navigate-goal (future, disabled)",
        recovery_path: "Require cloud idempotency key, robot ACK, cancel path, and task archive evidence before enabling.",
      },
      {
        id: "tts_preview",
        label: "TTS utterance envelope",
        status: "blocked_not_proven",
        requires_confirmation: true,
        sends_to_robot: false,
        cloud_endpoint: "POST /api/o7/operator/voice/tts (future, disabled)",
        recovery_path: "Require cloud TTS ACK and speaker-side failure event before any dispatch UI.",
      },
    ],
    blocked_reasons: [
      "cloud_realtime_api_draft",
      "pc_must_not_direct_connect_robot",
      "robot_ack_timeout_recovery_not_proven",
      "real_map_pose_stream_not_proven",
      "realtime_map_snapshot_blocked",
      "elevator_state_snapshot_blocked",
      "real_voice_stream_not_proven",
      "board_media_preflight_blocked",
      "manual_or_navigation_dispatch_disabled",
    ],
    not_proven: [
      "real_o7_realtime_cloud_stream",
      "real_robot_position_latency_lt_2s",
      "real_elevator_state_chain",
      "real_route_replay_archive",
      "real_annotation_submit_api",
      "real_asr_tts_runtime",
      "real_rtc_session",
      "real_camera_video_source",
      "real_audio_capture",
      "real_audio_playback",
      "real_tts_playback",
      "on_robot_media_smoke",
      "real_operator_safe_command_dispatch",
      "delivery_success",
    ],
    recovery_paths: [
      "Connect O6 cloud archive and realtime stream before replacing draft values.",
      "Collect board media preflight JSON and on-robot media smoke before interpreting KR5 fields.",
      "Ask Robot Software for robot-side ACK, timeout, cancel, and stop evidence before enabling commands.",
      "Ask Hardware for HIL/safety evidence before treating manual control as safe.",
    ],
  };
}
