# Trash collection action - navigate to trash, pick up, deliver to bin
string trash_goal_frame    # target frame to navigate to
int8 trash_type            # expected trash type
---
bool arrived               # successfully reached the trash
bool collected             # successfully picked up trash
bool delivered             # successfully delivered to bin
int8 status                # 0=idle, 1=navigating, 2=collecting, 3=delivering, 4=done
float64 elapsed_sec        # time elapsed
---
bool success               # overall task success
int8 items_collected       # number of items collected
int8 items_disposed        # number of items disposed
float64 total_duration_sec
string error_message
